### ISSUE TITLE
Missing imagery on mapbox (and imagery with issues)

### ISSUE THREAD

**Issue by ethanwhite** [weecology/EvergladesTools#108]
## Broken

fixed [X], site, date, notes

### New
- [ ] Jerrod, 2021-03-03, no images at any zoom. There are bird and nest predictions. This flight seems to have been added since we did the last image check because I have no records of there being a 3/3/21 Jerrod image in the app before.

### Two flights + names

- [ ] StartMel, 2021-04-07, no images at any zoom, **2 flights on the same date**
- [ ] AlleyNorth, 2021-02-18, no images at any zoom, **2 flights on the same date**
- [ ] CypressCity, 2022-04-21, no images on any zoom, **2 flights, name matching**
- [ ] Jerrod, 2022-04-11, "two separate flights (A and B) on mapbox so neither showing in app" true for all zooms, **2 flights, name matching**
- [ ] Vacation, 2021-03-31, no images at any zoom, **2 flights, name matching**

### Name matching

- [ ] AlleyNorth, 2021-03-23, no images on any zoom. Multiple samples checked, ortho name "AlleyNorth_03_23_2021_Central_Partial.tif", no mbtiles file, **name matching**, **partial flight**
- [ ] AlleyNorth, 2021-03-30, no images on any zoom. Multiple samples checked, ortho name "AlleyNorth_03_30_2021_North.tif", 0B mbtiles file, partial file on mapbox, **name matching**, **partial flight**
- [ ] AlleyNorth, 2021-04-20, no images on any zoom. Multiple samples checked, **name matching**,
- [ ] AlleyNorth, 2021-04-27, no images on any zoom. Multiple samples checked, **name matching**,
- [ ] CypressCity, 2022-05-25, no images on any zoom, **name matching**
- [ ] Vacation, 2022-05-19, no images at any zoom, **name matching**

### Partial flights, confirm that actual flight was partial

- [ ] AlleyNorth, 2021-02-23, "half flight showing, birds and imagery", current mbtiles is 0B, file on mapbox is partial
- [ ] AlleyNorth, 2021-03-16, "half flight showing, birds and imagery", current mbtiles is 0B, file on mapbox is partial
- [ ] AlleyNorth, 2021-04-06, "half flight showing, birds and imagery", current mbtiles 0B, **partial flight** on mapbox
- [ ] AlleyNorth, 2021-04-14, "half flight showing, birds and imagery", current mbtiles 0B, **partial flight** on mapbox

### Create Orthos

- [x] Jerrod, last flight 5/24/22 but ends 5/9 on app, orthos in Dropbox end on 5/9, **raw data for 5/24/22 exists but has not been orthorectified** #114
- [x] Vacation, last flight 6/9/22 but ends 6/1 on app, orthos in Dropbox end on 6/1, **raw data for 6/9/22 exists but has not been orthorectified** #114

### Fix Orthos

- [ ] JetportSouth, 2021-04-13, "large number of missing areas presumably due to orthrectification". it's like the gov't redacted the colony!, **redo orthorectification** #114
- [ ] JetportSouth, 2021-04-26, "large number of missing areas presumably due to orthrectification",  **redo orthorectification** #114

### Additional flights with issues

https://github.com/weecology/EvergladesTools/issues/38

## Should be fixed

- [ ] JetPortSouth. 2021-06-07
- [ ] JetPortSouth. 2021-06-20
- [ ] JetPortSouth. 2021-06-27

## Fixed
- [x] Jerrod, 2021-03-31, "wrong bands, all red", same issue on mapbox, **ortho was fine so rebuilt mbtiles and reuploaded**
- [x] 6thBridge, 2022-04-22, seems ok now
- [x] 6thBridge, 2022-03-17, images lost at highest zoom-in, stops at Z23 on mapbox, rebuilt mbtiles, **should be fixed**
- [x] 6thBridge, 2022-03-23,  no images at any zoom, mbtiles file is tiny, rebuilt mbtiles, **should be fixed**
- [x] 6thBridge, 2022-03-03, sample 1 ok, all others lost at highest zoom-in, **file on mapbox looks fine**
- [x] Joule, 2022-04-18
- [x] Joule, 2020-05-05, no mbtiles file, but good file on mapbox
- [x] Joule, 2020-05-29, "missing two coarsest resolution tiles", everything fine when zoomed in. middle zooms lose sections of colony that then reappear, no mbtiles file, file on mapbox seems OK
- [x] Joule, 2022-02-11, missing highest zoom-in, file on mapbox is to Z24
- [x] Joule, 2022-05-09, missing highest zoom-in, Z24 on mapbox
- [x] Vacation, 2022-02-11
 - [x] 6thBridge, 2021-03-11, no images at any zoom, mbtiles file create in Nov is 0 B, **rebuilt mbtiles**
- [x] Joule, 2020-04-07, "missing two coarsest resolution tiles",  everything fine when zoomed in. middle zooms lose sections of colony that then reappear as coarsest zoom, current mbtiles 0B, **rebuilt mbtiles**
- [x] Joule, 2020-03-31, "missing two coarsest resolution tiles", everything fine when zoomed in. middle zooms lose sections of colony that then reappear as coarsest zoom. current mbtiles 0B, **rebuilt mbtiles**
- [x] Joule, 2022-02-21, no images at any zoom,  tiny mbtiles file, file present but nothing displayed on mapbox, **rebuilt mbtiles**
- [x] StartMel, 2022-03-30, no images at any zoom, mbtiles file 0B, bad image on mapbox, **rebuilt mbtiles**
- [x] 6thBridge, 2022-02-19, images lost at two highest zoom-ins, version on mapbox is Z17-Z22 not Z17-Z24, **rebuilt mbtiles**
- [x] 6th Bridge, 2022-04-01, no images at any zoom (this one may have existed all along but might have been recorded as  2022-04-22, which magically fixed itself)
- [x] Joule, 2022-02-11, missing highest zoom-in, file on mapbox is to Z24 (this one was originally listed as broken, then fixed, but is currently broken again in the same way)
- [x] Joule, 2022-05-09, missing highest zoom-in, Z24 on mapbox (same issue as above)

**Comment by skmorgane** [comment]
JetPortSouth, 2021-02-15 through 2021-03-15. missing images? location is blank during this range but then a woodstork nest shows up so not an edge of colony issue.

**Comment by skmorgane** [comment]
JetPortSouth. 2021 June images, Flights in June are not up.

**Comment by skmorgane** [comment]
Joule, 2022-02-11
Joule, 2022-02-21

**Comment by skmorgane** [comment]
Don't know if this was fixed or if there was typo in date but
StartMel, 2022-02-11
is showing up

**Comment by bw4sz** [comment]
I have added a stop gap solution of turning the check if exists and parallel code run. The future is to get this merged into snakemake as well as merge two pieces of flights.

**Comment by bw4sz** [comment]
There may be other errors here.

If we look at start mel 3 30

The icon is black.
<img width="991" alt="image" src="https://user-images.githubusercontent.com/1208492/200918561-b2e28e50-02cc-4499-9fcb-6fca93fc247f.png">

**Comment by ethanwhite** [comment]
Most AlleyNorth flights in 2021 are partial. Some of them are labeled that way, which is causing name matching issues and no imagery. Some are not which is causing part of the imagery to be missing, but it doesn't exist.

**Comment by ethanwhite** [comment]
@skmorgane - when you get a chance can you check on this imagery. In concept we should be fixed at this point, but we might still be missing a few pieces that have issues in the workflow at some stage.

**Comment by henrykironde** [comment]
Any  Orthos that you may want to re / create?

**Comment by ethanwhite** [comment]
I believe we'd fixed all of this so closing for now. If there are still things missing or that have problems let's start a fresh issue, but link back here for context if it's something mentioned here.
